apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'io.github.tret9.redwood.schema'

dependencies {
  api projects.redwoodUiBasicSchema
  api projects.redwoodUiCoreSchema
}

redwoodSchema {
  type = 'com.example.redwood.testapp.TestSchema'

  // Private, test-only module. It does not need to be stable.
  apiTracking = false
}
